#' Plot read coverage graphs of contigs classified as Prophage-like, Sloping, or HighCovNoPattern
#'
#' Plot the read coverages of a contig and its associated pattern-match for Prophage-like,
#' Sloping and HighCovNoPattern classifications. Returns a list of ggplot objects.
#'
#' @param VLPpileup A dataframe containing contig names, coverages averaged over 100 bp windows, and contig positions associated with mapping VLP-fraction reads to whole-community contigs
#' @param WCpileup A dataframe containing contig names, coverages averaged over 100 bp windows, and contig positions associated with mapping whole-community reads to whole-community contigs
#' @param TrIdentResults Output from TrIdentClassifier
#' @param cleanup If pileup files are generated by BBMap, the .txt files can be input directly into TrIdent with cleanup=TRUE. The user is responsible for data cleaning/formatting if cleanup=FALSE.
#' @param matchScoreFilter Filter the results using a pattern match threshold. A suggested filtering threshold is found in the histogram after TrIdentClassifier is run. Default is no filtering.
#' @param saveFilesTo Provide a path to the directory you wish to save TrIdent plots to. TrIdent will create a folder within the provided directory to store results.
#' @export
#' @examples
#' data("VLPFractionSamplePileup")
#' data("WholeCommunitySamplePileup")
#' data("TrIdentSampleOutput")
#' patternMatches <- plotTrIdentResults(
#'                   VLPpileup=VLPFractionSamplePileup,
#'                   WCpileup=WholeCommunitySamplePileup,
#'                   TrIdentResults=TrIdentSampleOutput
#'                   )
plotTrIdentResults <- function(VLPpileup, WCpileup, TrIdentResults, matchScoreFilter, saveFilesTo, cleanup=TRUE) {
  position <- coverage <- NULL
  windowSize <- TrIdentResults[[5]]
  cleanSummaryTable <- TrIdentResults[[3]]
  summaryTable <- TrIdentResults[[1]]
  MSF <- ifelse(missing(matchScoreFilter) == TRUE, 0, matchScoreFilter)
  FilePath <- ifelse(missing(saveFilesTo) == TRUE, 0, saveFilesTo)
  if(cleanup == TRUE){
    VLPpileup <- pileupFormatter(VLPpileup)
    WCpileup <- pileupFormatter(WCpileup)
  }
  plots <- list()
  contigNames <- c()
  plots <- lapply(seq_along(cleanSummaryTable), function(i){
    contigName <- cleanSummaryTable[[i]][[9]]
    viralSubset <- changeWindowSize(VLPpileup[which(VLPpileup[,1] == contigName),], windowSize)
    microbialSubset <- changeWindowSize(WCpileup[which(WCpileup[,1] == contigName),], windowSize)
    patternMatchInfo <- summaryTable[which(summaryTable[,1] == contigName),]
    classification <- patternMatchInfo[,2]
    pattern <- patternBuilder(viralSubset, cleanSummaryTable, classification, i)
    patternMatch <- cbind(viralSubset, pattern)
    matchLength <- patternMatchInfo[,5]
    matchscoreQC <- (cleanSummaryTable[[i]][[1]]) / mean(viralSubset$coverage)
    if (MSF != 0) {if (matchscoreQC > MSF) return()}
    if (classification == "Sloping") subtitleInfo <- paste("Slope:", patternMatchInfo[10])
    else if (classification == "HighCovNoPattern") subtitleInfo <- paste("VLP:WC ratio:", patternMatchInfo[4])
    else if (classification == "Prophage-like") {
      if (is.na(patternMatchInfo[8]) == TRUE) subtitleInfo <- NULL
      else if (patternMatchInfo[8] == "Elevated") subtitleInfo <- "Active/highly abundant Prophage-like element"
      else if (patternMatchInfo[8] == "Depressed") subtitleInfo <- "Not homogenously integrated Prophage-like element"
      else subtitleInfo <- NULL
      }
    wholecomm_plot <- ggplot(data=microbialSubset, aes(x=position, y=coverage))+
      geom_area(fill="deepskyblue3") +
      labs(title=paste(contigName, "Classification:", classification),
           subtitle=paste("Matching-region size (bp):", matchLength, subtitleInfo),
           x=" ", y="Whole-community \n read coverage") +
      scale_x_continuous(expand = c(0, 0)) +
      theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(),
            panel.background=element_blank(), axis.line=element_line(colour="black"),
            text = element_text(size=14),
            axis.text = element_text(size=10),
            plot.margin=margin(t=0, r=6, b=0, l=2))

    Overlay_plot <- ggplot(data=patternMatch, aes(x=position, y=coverage))+
      geom_area(fill="deepskyblue3") +
      geom_line(aes(y=pattern), color="black", linewidth=1)+
      labs(x="Contig position (bp)", y="VLP-fraction \n read coverage")+
      scale_x_continuous(expand = c(0, 0)) +
      theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(),
            panel.background=element_blank(), axis.line=element_line(colour="black"),
            text=element_text(size=14),
            axis.text=element_text(size=10),
            plot.margin=margin(t=0, r=6, b=0, l=2))

    contigNames <<- c(contigNames, contigName)
    combined_plot <- (wholecomm_plot / Overlay_plot)
    combined_plot
  })
  plots <- Filter(Negate(is.null), plots)
  names(plots) <- contigNames
  if (FilePath != 0) {
    ifelse(!dir.exists(paths=paste0(FilePath, "\\TrIdentOutput")),
           dir.create(paste0(FilePath, "\\TrIdentOutput")),
           print("'TrIdentOutput' folder exists already in the provided directory"))
    lapply(names(plots),
           function(X)ggsave(filename=paste0(FilePath, "\\TrIdentOutput\\", X, ".png"), plot=plots[[X]],
                             width=8, height=4))
    return(plots) } else return(plots)
}
