#' Plot read coverage graphs of contigs classified as Prophage-like, Gen/Lat/GTA, or HighVLPWCRC
#'
#' Plot the read coverages of a contig and its associated pattern-match for each contig classified as prophage-like, gen/lat/GTA or none with high VLP-fraction:whole-community read coverage ratios. Returns a list of plot objects.
#'
#' @param VLP_pileup A dataframe containing contig names, coverages averaged over 100bp windows, and contig positions associated with mapping VLP-fraction reads to whole-community contigs
#' @param WC_pileup A dataframe containing contig names, coverages averaged over 100bp windows, and contig positions associated with mapping whole-community reads to whole-community contigs
#' @param transductionclassifications Output from TrIdent_Classifier
#' @param cleanup If pileup files are generated by BBMap's pileup.sh, the files output from pileup.sh can be input directly into TrIdent with cleanup=TRUE. If your pileup files are NOT generated with BBMap's pileup.sh, set cleanup=FALSE. The user is responsible for data cleaning/formatting if this option is used.
#' @export
#'
#' @examples
#' \dontrun{
#' pattern_matches <- Plot_TrIdentPatternMatches(VLP_pileup=VLP_fracreadcov, WC_pileup=whole_commreadcov, transductionclassifications=TrIdent_results)
#' pattern_matches$NODE_1
#' }
Plot_TrIdentPatternMatches <- function(VLP_pileup, WC_pileup, transductionclassifications, cleanup=TRUE) {
  position <- coverage <- NULL
  windowsize <- transductionclassifications[[5]]
  transductionclassifications_wlowratios <- transductionclassifications[[3]]
  final_summary_table <- transductionclassifications[[1]]
  if(cleanup==TRUE){
    VLP_pileup <- readcovdf_formatter(VLP_pileup)
    WC_pileup <- readcovdf_formatter(WC_pileup)
  }
  plots <- list()
  ref_names <- c()
  plots<-lapply(1:length(transductionclassifications_wlowratios), function(i){
    ref_name <- transductionclassifications_wlowratios[[i]][[9]]
    ref_names <- c(ref_names, ref_name)
    viral_subset <- VLP_pileup[which(VLP_pileup[,1] == ref_name),]
    viral_subset <- windowsize_func(viral_subset,windowsize)
    microbial_subset <- WC_pileup[which(WC_pileup[,1] == ref_name),]
    microbial_subset <- windowsize_func(microbial_subset,windowsize)
    match_info <- final_summary_table[which(final_summary_table[,1]==ref_name),]
    classification <- match_info[,2]
    pattern <- pattern_builder(viral_subset, transductionclassifications_wlowratios, classification, i)
    pattern_match <- cbind(viral_subset, pattern)
    match_length <- match_info[,3]
    classification <- match_info[,2]
    if (is.na(match_info[6]) == TRUE){
      prophage_activity <- NULL
    } else if (match_info[6]=="YES"){
      prophage_activity <- "Active/highly abundant prophage"
    } else if (match_info[6]=="MIXED"){
      prophage_activity <- "Not-homogenously present/integrated"
    } else {
      prophage_activity <- NULL
    }
    wholecomm_plot <- ggplot(data=microbial_subset, aes(x=position, y=coverage))+
      geom_area(fill="deepskyblue3") +
      labs(title=paste(ref_name, "Classification:", classification ),subtitle=paste("Matching-region size (bp):", match_length, prophage_activity), x=" ", y="Whole-community \n read coverage") +
      theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
            panel.background = element_blank(), axis.line = element_line(colour = "black"),
            text = element_text(size = 14),
            axis.text = element_text(size=10),
            plot.margin=margin(t = 0, r = 0, b = 0, l = 2))

    Overlay_plot <- ggplot(data=pattern_match, aes(x=position, y=coverage))+
      geom_area(fill="deepskyblue3") +
      geom_line(aes(y=pattern), color="black", size=1)+
      labs(x="Contig position (bp)", y="VLP-fraction \n read coverage")+
      theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
            panel.background = element_blank(), axis.line = element_line(colour = "black"),
            text = element_text(size = 14),
            axis.text = element_text(size=10),
            plot.margin=margin(t = 0, r = 0, b = 0, l = 2))

    combined_plot <- (wholecomm_plot/Overlay_plot)
    combined_plot
  })
  names(plots) <- ref_names
  return(plots)
}
