#' Identify potential specialized transduction events on contigs classified as Prophage-like
#'
#' Search contigs classified as Prophage-like for dense read coverage outside of the pattern-match borders
#' that may indicate specialized transduction. Returns a list with the first object containing a summary table
#' and the second object containing a list of plots of with associated specialzied transduction search results.
#' If the plot is green, it has been identified as having potential specialized transduction.
#'
#' @param VLPpileup A table containing contig names, coverages averaged over 100 bp windows, and contig positions associated with mapping VLP-fraction reads to whole-community contigs
#' @param TrIdentResults Output from TrIdentClassifier
#' @param noReadCov How many bp of no read coverage are encountered before specialized transduction searching stops? Default is 500.
#' @param specTransLength How many bp of read coverage are needed for specialized transduction to be considered? Default is 2000.
#' @param specificContig Provide the name of a specific contig if you would like to search only that contig.i.e. "NODE_1"
#' @param cleanup If pileup files are generated by BBMap, the .txt files can be input directly into TrIdent with cleanup=TRUE. The user is responsible for data cleaning/formatting if cleanup=FALSE.
#' @param matchScoreFilter Filter results to only display contigs that recieved a pattern-match score below the chosen cutoff. Defualt is infinity (i.e no filter)
#' @param logScale If TRUE, coverage is plotted in log10. If FALSE, raw coverage values are plotted. Default is FALSE.
#' @export
#' @examples
#' data("VLPFractionSamplePileup")
#' data("TrIdentSampleOutput")
#'
#' specTransduction <- specializedTransductionID(
#'                     VLPpileup=VLPFractionSamplePileup,
#'                     TrIdentResults=TrIdentSampleOutput
#'                     )
#'
#' specTransductionNODE44 <- specializedTransductionID(
#'                           VLPpileup=VLPFractionSamplePileup,
#'                           TrIdentResults=TrIdentSampleOutput,
#'                           specificContig="NODE_44"
#'                           )
 specializedTransductionID <- function(VLPpileup, TrIdentResults, specificContig, noReadCov=500, specTransLength=2000, matchScoreFilter=Inf, logScale=FALSE, cleanup=TRUE){
  specTransInfo <- NULL
  TrIdentResultPatterns <- TrIdentResults[[3]]
  TrIdentResultSumm <- TrIdentResults[[1]]
  windowSize <- TrIdentResults[[5]]
  specTransSumm <- data.frame(matrix(ncol=6, nrow=0))
  colnames(specTransSumm) <- c("contigName", "Specialized_transduction", "Left", "Right", "Length_left", "Length_right")
  if (cleanup == TRUE) VLPpileup <- pileupFormatter(VLPpileup)
  specificContig <- ifelse(missing(specificContig), NA, specificContig)
    specTransCount <- 0
    plots <- list()
    J <- 1
    lapply(seq_along(TrIdentResultPatterns), function(i) {
      classification <- TrIdentResultPatterns[[i]][[8]]
      contigName <- TrIdentResultPatterns[[i]][[9]]
      normMatchScore <- TrIdentResultSumm[which(TrIdentResultSumm[,1] == contigName), 3]
      if(is.na(specificContig)) {
        if (classification == "Prophage-like" & normMatchScore < matchScoreFilter) {
          specTransInfo <<- specTransductionSearchAndPlot(contigName, VLPpileup, TrIdentResultPatterns, TrIdentResultSumm,
                                                          windowSize, i, noReadCov, specTransLength, logScale)
          if(specTransInfo[[1]][[2]] == "yes") specTransCount <<- specTransCount + 1
          specTransSumm[J,c(1:6)] <<- specTransInfo[[1]]
          plots[[J]] <<- specTransInfo[[2]]
          J <<- J+1
   }} else if (contigName == specificContig & classification == "Prophage-like" & normMatchScore < matchScoreFilter) {
            specTransInfo <<- specTransductionSearchAndPlot(contigName, VLPpileup, TrIdentResultPatterns, TrIdentResultSumm,
                                                            windowSize, i, noReadCov, specTransLength, logScale)
            if(specTransInfo[[1]][[2]] == "yes") specTransCount <<- specTransCount + 1
            specTransSumm[J,c(1:6)] <<- specTransInfo[[1]]
            plots[[J]] <<- specTransInfo[[2]]
            J <<- J+1
          }
         })
    if (specTransCount == 0) stop ("Selected contig is either not prophage-like, spelled incorrectly or has a match score below the chosen matchScoreFilter")
    message(paste(specTransCount, "contigs have potential specialized transduction"))
    names(plots) <- specTransSumm[,1]
    specTransList <- list(summaryTable=specTransSumm, Plots=plots)
    return(specTransList)
    }

