#' Classify contigs as Prophage-like, Gen/Lat/GTA, None, or HighVLPWCratio
#'
#' Classifies contigs as prophage-like, gen/lat/GTA, none, or highVLPWCratio. This function performs all the pattern-matching and summarizes the results into a list. The first item in the list is a table consisting of the summary information of all the contigs that passed through pattern-matching (i.e were not filtered out). The second item in the list is a table consisting of the summary information of all contigs that were predicted as containing a potential prophage, generalized, lateral or GTA (Gen/Lat/GTA) transduction and/or low whole-community: VLP-fraction read coverage ratios. The third item in the list contains the best pattern-match information associated with each contig in the previous table. The fourth object in the list is a table containing the contigs that were filtered out prior to pattern_matching and the reason why. The fifth item is the windowsize used for the search.
#'
#'@param VLP_pileup A dataframe containing contig names, coverages averaged over 100bp windows, and contig positions associated with mapping VLP-fraction reads to whole-community contigs
#'@param WC_pileup A dataframe containing contig names, coverages averaged over 100bp windows, and contig positions associated with mapping whole-community reads to whole-community contigs
#'@param windowsize The number of base pairs to average coverage values over. Options are 100, 200, 500, 1000 and 2000 ONLY. Larger window sizes improve processing time but the resolution of read coverage patterns may be lost. Default is 1000bp.
#'@param cleanup If pileup files are generated by BBMap's pileup.sh, the files output from pileup.sh can be input directly into TrIdent with cleanup=TRUE. If your pileup files are NOT generated with BBMap's pileup.sh, set cleanup=FALSE. The user is responsible for data cleaning/formatting if this option is used.
#'@param minblocksize The minimum size of the prophage-like block pattern. Default is 10000 bp.
#'@param maxblocksize The maximum size of the prophage-like block pattern. Default is NA
#'@param mincontiglength The minimum contig size (in bp) to perform pattern-matching on. Contigs smaller than this threshold will be filtered out. Default is 30,000bp
#'@param SaveFilesTo Provide a path to the directory you wish to save TrIdent output summary tables to. TrIdent will make a folder within the provided directory to store results. This parameter is useful if running TrIdent on the command line.
#'@export
#'
#'@examples \dontrun{
#'TrIdent_results <- TrIdent_Classifier(VLP_pileup=VLP_fracreadcov, WC_pileup=whole_commreadcov, windowsize=1000, minblocksize=10000, maxblocksize=150000, mincontiglength=30000, SaveFilesTo="C://Users//Path//to//Folder", cleanup=TRUE)
#'}
  TrIdent_Classifier <- function(VLP_pileup, WC_pileup, windowsize = 1000, minblocksize=10000, maxblocksize=Inf, mincontiglength=30000, SaveFilesTo, cleanup=TRUE){

    #error catching
    if(!(windowsize %in% list(100,200,500,1000,2000))){
      stop("windowsize must be either 100, 200, 500, 1000 or 2000!")
    }
    if(minblocksize <= 2000){
      stop("Block size must be greater than 2000")
    }
    VLP_pileup <- readcovdf_formatter(VLP_pileup)
    WC_pileup <- readcovdf_formatter(WC_pileup)
    if(nrow(VLP_pileup)!=nrow(WC_pileup)){
      stop("Something has gone wrong: VLP and WC pileup files have differing row numbers")
    }
    if(abs(VLP_pileup[1,3]-VLP_pileup[2,3]) != 100|abs(WC_pileup[1,3]-WC_pileup[2,3]) != 100){
      stop("pileup files MUST have a windowsize/binsize of 100!")
    }

    #main algorithm start
    start_time <- Sys.time()
    cat("Starting pattern-matching... \n")
    SM_classifications_summary <- pattern_matcher(VLP_pileup, WC_pileup, windowsize, minblocksize, maxblocksize, mincontiglength)
    cat("Identifying potential transducing events \n")
    cat("Determining sizes (bp) of potential transduction events \n")
    cat("Identifying highly active/abundant prophage-like elements \n")
    summary_table_final <- slope_summary(
      prophagelikeactivity_checker(
        matchsize_checker(
          WCVF_ratio_calculator(
            contig_classification_summary(SM_classifications_summary[[1]]),
          WC_pileup, VLP_pileup),
        alltransduction_events_summarylist(SM_classifications_summary[[1]]), windowsize),
      allprophagelike_matches(SM_classifications_summary[[1]]), VLP_pileup, WC_pileup, windowsize),
    allgenlatGTA_matches(SM_classifications_summary[[1]]))

    cat("Finalizing output \n")
    final_summary_list<-list(summary_table_final,
                             summary_table_final[which(summary_table_final[,2]=="Prophage-like"|summary_table_final[,2]=="Gen/Lat/GTA"|summary_table_final[,2]=="HighVLPWCReadCov"),],
                             alltransduction_withlowratios_summarylist(SM_classifications_summary[[1]], summary_table_final),
                             SM_classifications_summary[[2]],
                             windowsize)
    names(final_summary_list) <- c("Full_summary_table", "Cleaned_summary_table", "PatternMatchInfo", "FilteredOutContig_table", "Windowsize")
    end_time <- Sys.time()
    cat(paste("Execuion time:", end_time-start_time, "\n"))
    cat(paste(length(which(SM_classifications_summary[[2]][,2]=="Low VLP-fraction read cov")), "contigs were filtered out based on low read coverage \n"))
    cat(paste(length(which(SM_classifications_summary[[2]][,2]=="Contig length too small")), "contigs were filtered out based on length \n"))
    print(table(final_summary_list[[1]][,2]))
    cat(paste(length(which(final_summary_list[[1]][,6]=="YES")), "of the predicted prophages/prophage-like elements are highly active or abundant \n"))
    cat(paste(length(which(final_summary_list[[1]][,6]=="MIXED")), "of the predicted prophages/prophage-like elements are not homogenously integrated into their bacterial host population \n  \n"))
    print(SM_classifications_summary[[3]])
    if(missing(SaveFilesTo)==FALSE){
      ifelse(!dir.exists(paths=paste0(SaveFilesTo, "\\TrIdentOutput")), dir.create(paste0(SaveFilesTo, "\\TrIdentOutput")), print("'TrIdentOutput' folder exists already in the provided directory"))
      write.table(summary_table_final, file = paste0(SaveFilesTo,"\\TrIdentOutput\\summary_table.csv"), sep = ",", row.names = FALSE)
      write.table(summary_table_final[which(summary_table_final[,2]=="Prophage-like"|summary_table_final[,2]=="Sloping"|summary_table_final[,2]=="HighCoverageNoPattern"),],
                  file = paste0(SaveFilesTo,"\\TrIdentOutput\\summary_table_cleaned.csv"), sep = ",", row.names = FALSE)
      ggsave(filename= paste0(SaveFilesTo, "\\TrIdentOutput\\MatchScoreDensityPlot.png"), plot=SM_classifications_summary[[3]],
             width = 4, height = 4)
      return(final_summary_list)
    }else{
      return(final_summary_list) 
    }
}
